### PR TITLE
CUDA Fortran port of serial CloverLeaf

### PR DESCRIPTION
**Pull request by gruetsch**

### CODE REVIEW

**Comment by waynegaudin** [comment]
Apologies that I have only just seen this. I'll make sure it gets put in a main repo. We are just about to reorganise the structure so it is just the right time.

**Comment by gruetsch** [comment]
Hi Wayne:

I’m attaching an updated version of the CUDA Fortran port of CloverLeaf.  You mentioned you’ll be updating the CloverLeaf website at some point, and this is the version that should be posted rather than the version in the pull request.  There are a few bug fixes in this (added missing synchronizations in visit.f90), some optimizations, and updated compiler flags.  I’ll be presenting a short talk on this at GTC in a few weeks.
- Greg

---

This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by

## reply email and destroy all copies of the original message.

**Comment by waynegaudin** [comment]
Hi Greg

That's great news. We'll include it on our new website.

Should there be a tar or zip file attached?

Thanks

Wayne

**Comment by gruetsch** [comment]
There should have been a tarball.  Let me know if it doesn’t come through this time.
- Greg

---

This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by

## reply email and destroy all copies of the original message.

**Comment by waynegaudin** [comment]
I can't see it but it might because I am on my mobile. I'll check tomorrow
from a pc.

**Comment by waynegaudin** [comment]
Hi Matt

I have asked a colleague to make sure this gets added to our UK-MAC site,
as I am on leave for 5 weeks after today.

His email is oliver.perks@awe.co.uk and he should in touch very soon.

I still can't see an attachment but maybe I am not using git correctly.
Olly will be able to sort this out as he knows what he is doing!

Thanks for expanding the reach of our mini-apps.

Wayne

**Comment by OliverPerks** [comment]
Hi @gruetsch ,
Sorry about this. It sadly fell off of my radar.

Like Wayne I can only see the pull request and not the attachment.

Could you please try to send it again, and I will get it integrated.

Thanks,
Olly

**Pull request closed without merging**
